### ISSUE TITLE
Saving files is not properly implemented

### ISSUE THREAD

**Issue by nottux** [linux-source-tools/gimp-plugin-vtf#2]
i have created 512x512 image file in gimp but exported file is broken:
[issue.zip](https://github.com/linux-source-tools/gimp-plugin-vtf/files/1887712/issue.zip)

also i can't find any documentation, is it the exact  software of https://github.com/Artfunkel/gimp-vtf/releases
i have tried everything but all files exported were 104 bytes
```
[utku@utku2 ~]$ gimp --version
GNU Görüntü İşleme Programı sürüm 2.8.22
```
i am using antergos

**Comment by Rahix** [comment]
I can confirm that this issue exists, but unfortunately I do not have a quick fix available. As I haven't written the code for this plugin (this repo is just a fork), I would need some time to look into it.

> is it the exact software of https://github.com/Artfunkel/gimp-vtf/releases

No, the original repo is https://github.com/lxndr/vtf, which does not relate to the windows implementation you linked in any way as far as I'm aware.

**Comment by Rahix** [comment]
@tuxutku: Just a heads up, I have pushed an update that should make saving `.vtf`-files work

**Comment by TheAwesome98-Real** [comment]
> @tuxutku: Just a heads up, I have pushed an update that should make saving `.vtf`-files work

Didn’t work on my machine, and a few others’.
