### ISSUE TITLE
Makefile doesn't work.

### ISSUE THREAD

**Issue by LaggyAsBalls** [linux-source-tools/gimp-plugin-vtf#6]
I'm sorry, I am a bit of a Linux nub. I get this error when I type make in the file. **It might be because Gimp is either too new or Preinstalled**?
Output:
$ make
gcc -Wall -g -o file-vtf dxt.c vtf.c gimp-plugin-vtf.c `pkg-config --cflags --libs gimp-2.0 gimpui-2.0 gtk+-2.0`
Package gimp-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gimp-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gimp-2.0', required by 'virtual:world', not found
Package 'gimpui-2.0', required by 'virtual:world', not found
vtf.c:4:10: fatal error: glib/gstdio.h: No such file or directory
    4 | #include <glib/gstdio.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
gimp-plugin-vtf.c:2:10: fatal error: libgimp/gimp.h: No such file or directory
    2 | #include <libgimp/gimp.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:5: file-vtf] Error

**Comment by Rahix** [comment]
Judging by your other [comment](https://github.com/linux-source-tools/gimp-plugin-vtf/pull/5#pullrequestreview-587254931), you got it working now?


By the way, don't expect too much from this plugin... I just forked it here to collect utilities for using the source engine in Linux but didn't really have time to improve the plugin itself :/

**Comment by LaggyAsBalls** [comment]
Yes, I'm just very stupid. Yes, I got it working. I didn't have the right
dependencies like I said.
